#!/bin/bash
#
# pre-commit hook for Git which cancels the commit if tests fail.
#
# Install with:
#
#   (cd .git/hooks; ln -s ../../pre-commit .)
#
function display() {
  echo -e '\e[0;33m' $* '\e[0m'
}

display Python 2
py.test || exit 1

display Python 3
py.test-3 || exit 1
